### ISSUE TITLE
How to export smpl model with the joints, trans, beta and etc. info?

### ISSUE THREAD

**Issue by Stomachache007** [athn-nik/teach#14]
I would like to export the smpl model with joints, trans and beta information. Any idea how I get it?

**Comment by atnikos** [comment]
From the interact_teach script or in general? The idea is if you wan to export the motions generated from the inference code? Actually I save it [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/interact_teach.py#L86). In case you want the rotations you can add a line [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/model/teach.py#L164) and save the `rots` and `transl` variables `forward_seq` -- which are the rotations and translation in SMPL format. The betas are not really used so you can set them to zeros. The joint positions are the ones one line below `.joints` and can also be returned from `forward_seq` if you pass the argument `return_type=joints` instead of vertices.

**Comment by Stomachache007** [comment]
> From the interact_teach script or in general? The idea is if you wan to export the motions generated from the inference code? Actually I save it [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/interact_teach.py#L86). In case you want the rotations you can add a line [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/model/teach.py#L164) and save the `rots` and `transl` variables `forward_seq` -- which are the rotations and translation in SMPL format. The betas are not really used so you can set them to zeros. The joint positions are the ones one line below `.joints` and can also be returned from `forward_seq` if you pass the argument `return_type=joints` instead of vertices.




Hi athn-nik, thanks for your reply.
What I want is motions which can be exported into blender(https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon/-/blob/master/__init__.py) as animation.
It needs smplx joints 55 * 3 and  transl 1 * 3 info.

I tried 
```python
        from teach.transforms.smpl import RotTransDatastruct
        final_datastruct = self.Datastruct(rots_=RotTransDatastruct(rots=rots, trans=transl))
        print("joints ",final_datastruct.joints.shape)
        print("vertices ", final_datastruct.vertices.shape)
        if return_type == "vertices":
            return final_datastruct.vertices
        elif return_type == "joints":
            return final_datastruct.joints
        else:
            raise NotImplementedError
```
and find the output joints and vertices have exactly the same shape:

> joints  torch.Size([270, 6890, 3])
vertices  torch.Size([270, 6890, 3])

I assume joints size should me much smaller than vertices 6890.
So may I ask how to get the joints with 55*3?

thanks.

**Comment by atnikos** [comment]
So to do this you must take the rots and trans and pad the with zeros [for the extra joints] up to 55 and then it should work. Note that the joint you refer to I think are the SMPL rotations and not the joint positions referred as joints in the code. So you take the rots pad them with zeros to fit your purpose and the translation does the job you want to(transl.) put an extra line above the return type to save them and use them in blender

**Comment by atnikos** [comment]
Let me know, how this goes so I can close this.

**Comment by Stomachache007** [comment]
Hi athn-nik, 
1. I print transl by 
```python
        print("transl ", transl.shape)
```
before [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/model/teach.py#L164).
got

>         transl  torch.Size([180, 3])
I assume this is the transl needed for blender animation. please correct me if you  think I am wrong.

2. Besides this transl, to convert smpl data to a blender animation, the real poses(which I guess is joints information) is also needed, not the rots + trans + pad, it should be real poses. Transfer smpl to animation is desecribed
[here](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon/-/blob/master/__init__.py#L981)
and the 55 joints name are
[here](https://gitlab.tuebingen.mpg.de/jtesch/smplx_blender_addon/-/blob/master/__init__.py#L47)


To get the joints I tried two things 2.a and 2.b:

- [ ] first thing I tried is at [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/transforms/rots2joints/smplh.py#L127)

 I add
```python
 print("smpl_output ", smpl_output.joints.shape)
```
    
find this smpl_output is batch_size * 73 * 3, this is the final smplh joints info right? Can I transfer it into a smplx? Because I only saw blender support smplx.

- [x] second thing I tried to get the smpl joints is at  [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/model/teach.py#L165)
I add
```python
        print("joints shape ",final_datastruct.joints.shape)
        print("joints ", final_datastruct.joints.detach().cpu().numpy()[0])
        print("vertices shape", final_datastruct.vertices.shape)
        print("vertices ", final_datastruct.vertices.detach().cpu().numpy()[0])
```
got

> 
> joints shape  torch.Size([180, 6890, 3])
>
> joints  [[-0.26980534  0.01313967  1.5121334 ]
>  [-0.26402193  0.01042563  1.4962435 ]
>  [-0.26557612 -0.00282052  1.5022819 ]
>  ...

>
> vertices shape torch.Size([180, 6890, 3])
>
> vertices  [[-0.26980534  0.01313967  1.5121334 ]
>  [-0.26402193  0.01042563  1.4962435 ]
>  [-0.26557612 -0.00282052  1.5022819 ]
>  ...

>
> motion shape  torch.Size([180, 6890, 3])

while the vertices and joints look exactly the same. I think these are not the joints. may be a bug here.


So may I ask how I can get the smplx joints info? 

ps:As I saw you only implement smplh, do I need to implement something for smplx?

thanks.

**Comment by atnikos** [comment]
Let me try to explain.
The joints vertices point 3 seems like my bug but it is irrelevant for what you want to do. The poses you need are the SMPL poses which are the joint rotations not the joint positions. The 55 joints are kind of irrelevant and are the joint positions you need the rotations. 

As I said in the previous comment you can get the rotations in [here](https://github.com/athn-nik/teach/blob/49c1f157a63bed6b0ae81a70eeb006f7cb85fc0d/teach/model/teach.py#L164). Just add a line to save them like pickle or np save . The variables you need are `rots` and `transl` from that line which are the rotations and translation. 

I am using SMPL right now and SMPL is enough for my training data because AMASS has almost zero face and hand expressions (the rest of the joints beyond of the first 22). So save those joints and translation. Those are the real poses you refer to. Next because there is no motion for the rest you can just set them to zero  to make the target shape that the plugin accepts compatible with the the shape of the motion.

**Comment by Stomachache007** [comment]
thanks athn-nik,
Let me try later(it may takes sometime, a bit busy now). And update feedback with you.

**Comment by zhuangzhuang000** [comment]
> thanks athn-nik, Let me try later(it may takes sometime, a bit busy now). And update feedback with you.

Hello, have you got the position of the joints? Could you share the method with me? Thank you!

**Comment by atnikos** [comment]
If you set the
`model.rots2joints.jointstype = mmm` it will return the joints.

**Comment by zhuangzhuang000** [comment]
> If you set the `model.rots2joints.jointstype = mmm` it will return the joints.

Hello! Thank you for your reply, but I still have some questions. Where should I return the result?

 I tried to set the 'model.transforms.rots2joints.jointstype = "mmm"' in 【interact_teach.py】, and I also tried to change the 'return_type='joints'' in 【interact_teach.py】, but the results I got are all the same shape (motion shape torch.Size([60, 6890, 3])), it is the same as the last questioner. 

What I want is the position of joints, I think the shape shold be [frame, number of joints, 3], where did I make a mistake? Could you help me?

**Comment by atnikos** [comment]
Have you tried changing the line `model.transforms.rots2joints='vertices'` to the `interact_teach.py`?

**Comment by zhuangzhuang000** [comment]
> Have you tried changing the line `model.transforms.rots2joints='vertices'` to the `interact_teach.py`?

Thank you! I set the 'model.transforms.rots2joints.jointstype = "mmm" and 'return_type='joints'' , it works!

**Comment by atnikos** [comment]
You 're welcome, I will change the code to make it more obvious

**Comment by yufu-liu** [comment]
Hi, guys! 
Thanks for these detailed steps to get rotation and translation/position.

After getting all the information, I wonder that is there any difference between generated translation  and orignal translation in AMASS? 
Because I plotted the mesh with translation and rotation instead of plotting with vertices like the code, my mesh has a drift problem.
