### ISSUE TITLE
Where to download the SMPLH_MALE.pkl file?

### ISSUE THREAD

**Issue by Xiyan-Xu** [athn-nik/teach#2]
Thanks for great work!
I want to know where to download the SMPLH_MALE.pkl file. It seems there is no corresponding file on the smplx website (https://smpl-x.is.tue.mpg.de/download.php).

I tried to download SMPLH_male.pkl file from https://mano.is.tue.mpg.de/download.php, according to https://github.com/vchoutas/smplx/issues/10. But unfortunately, it caused an error:

> Traceback (most recent call last):
  File "E:\TeachLocal\teach\scripts\process_amass.py", line 262, in <module>
    db = read_data(input_dir, model_type, output_dir, use_betas, gender)
    final_seq_data = process_sequence(seq, use_betas, gender)
  File "E:\TeachLocal\teach\scripts\process_amass.py", line 175, in process_sequence
    bodymodel_seq = get_body_model(model_type, gender_of_seq if gender=='amass' else gender,
  File "E:\TeachLocal\teach\.\teach\transforms\smpl.py", line 171, in get_body_model
    body_model = smplx.create(body_model_path, model_type=type,
  File "C:\ProgramData\Anaconda3\envs\teach\lib\site-packages\smplx\body_models.py", line 2402, in create
    return SMPLH(model_path, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\teach\lib\site-packages\smplx\body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'

**Comment by atnikos** [comment]
I am not sure on the exact file that I used but it was pickle and I cannot release it here. But let me try to help because this is important.
Did you download the pickle for AMASS or the other ones.
Can you try doing the procedure for AMASS to extract the `SMPLH_MALE.pkl`? Described [here](https://github.com/vchoutas/smplx/blob/master/tools/README.md#smpl-h-version-used-in-amass). Let me know if it works.

**Comment by Xiyan-Xu** [comment]
It works!  Thanks a lot!

**Comment by Pavankunchala** [comment]
Can you send  me the Link to download `SMPLH_MALE.pkl` model

**Comment by atnikos** [comment]
Unfortunately i cannot directly release it due to licensing issues. You can download from [here](https://mano.is.tue.mpg.de/download.php) the ones for AMASS. Then you can try the process described [here](https://github.com/vchoutas/smplx/blob/master/tools/README.md#smpl-h-version-used-in-amass) to get the final `pkl`. That will give you the final pickle to use.
